//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialFashion.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLike
    {
        public int StatusLikeId { get; set; }
        public int StatusId { get; set; }
        public int UserId { get; set; }
        public byte Type { get; set; }
    }
}
