//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialFashion.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusId { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime Date { get; set; }
        public byte Privacy { get; set; }
        public string MoreImages { get; set; }
        public string Content { get; set; }
    }
}
